apiVersion: v1
kind: Service
metadata:
  name: voter-modify-api-service
spec:
  selector:
    app: voter-modify-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
